# Support Jarvis development
# Choose the platforms that work best for you - you don't need to use all of them

# GitHub Sponsors (recommended) - no fees, integrated with GitHub
github: [isair]

# Ko-fi for one-time donations - simple "buy me a coffee" style
ko_fi: isair
