# Build Jarvis Windows executable (PyInstaller onedir -> dist\Jarvis\Jarvis.exe)
# Uses .venv in the project root, or .mamba_env if present.

$ErrorActionPreference = "Stop"
$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $ProjectRoot

$Python = Join-Path $ProjectRoot ".venv\Scripts\python.exe"
if (-not (Test-Path $Python)) {
    $Python = Join-Path $ProjectRoot ".mamba_env\python.exe"
}
if (-not (Test-Path $Python)) {
    Write-Host "ERROR: No .venv or .mamba_env Python found. Create a venv and pip install -r requirements.txt"
    exit 1
}

Write-Host "Using Python: $Python"

$gitSha = "local"
try {
    $gitSha = (& git rev-parse --short=7 HEAD 2>$null)
    if (-not $gitSha) { $gitSha = "local" }
} catch {
    $gitSha = "local"
}
$devVersion = "dev-$gitSha"
$versionPath = Join-Path $ProjectRoot "src\jarvis\_version.py"
@"
# Auto-generated by scripts/build_exe.ps1
VERSION = "$devVersion"
RELEASE_CHANNEL = "develop"
"@ | Set-Content -Path $versionPath -Encoding utf8
Write-Host "Version: $devVersion"

Write-Host "Generating icons..."
& $Python src\desktop_app\desktop_assets\generate_icons.py
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

if (Test-Path build) { Remove-Item -Recurse -Force build }
if (Test-Path dist) { Remove-Item -Recurse -Force dist }

Write-Host "Running PyInstaller (this may take several minutes)..."
& $Python -m PyInstaller jarvis_desktop.spec
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$exe = Join-Path $ProjectRoot "dist\Jarvis\Jarvis.exe"
if (-not (Test-Path $exe)) {
    Write-Host "ERROR: Build failed - $exe not found"
    exit 1
}

Write-Host ""
Write-Host "SUCCESS"
Write-Host "  Executable: $exe"
Write-Host "  Folder:     $(Join-Path $ProjectRoot 'dist\Jarvis')"
Write-Host ""
Write-Host "Run Jarvis.exe from dist\Jarvis. Keep the whole folder together."
