"""Markdown report generation (local only)."""

from __future__ import annotations

from typing import Any

from jarvis.security.redact_ext import sanitize_for_html


def render_markdown_report(
    *,
    snapshot: dict[str, Any],
    scores: dict[str, Any],
    alerts: list[dict[str, Any]],
    changes: dict[str, Any],
    protection: list[dict[str, Any]],
) -> str:
    overall = scores.get("overall") or {}
    lines = [
        "# Cora Security Center Report",
        "",
        f"- Host: `{snapshot.get('host')}`",
        f"- Collected (UTC): `{snapshot.get('collected_at_utc')}`",
        f"- Mode: **READ-ONLY**",
        f"- Overall risk score: **{overall.get('score', 'n/a')}/100**",
        "",
        "> Absence of detections is **not** a certificate that the system is clean.",
        "",
        "## Scores",
        "",
    ]
    for key, card in scores.items():
        lines.append(f"### {card.get('name', key)}")
        lines.append(f"- Score: **{card.get('score')}**/100")
        lines.append(f"- Confidence: {card.get('confidence')}")
        lines.append(f"- Explanation: {card.get('explanation')}")
        if card.get("evidence"):
            lines.append("- Evidence:")
            for e in card["evidence"][:12]:
                lines.append(f"  - {e}")
        if card.get("limitations"):
            lines.append("- Limitations:")
            for e in card["limitations"][:8]:
                lines.append(f"  - {e}")
        lines.append("")

    lines += ["## Protection Status", ""]
    for p in protection:
        lines.append(f"- **{p.get('name')}**: {p.get('state')} — {p.get('detail')}")
    lines.append("")

    lines += ["## Active Alerts", ""]
    if not alerts:
        lines.append("_No alerts generated in this run._")
    for a in alerts[:50]:
        lines.append(f"### [{a.get('severity')}] {a.get('title')}")
        lines.append(f"- Category: {a.get('category')}")
        lines.append(f"- Status: {a.get('status')}")
        lines.append(f"- Reason: {a.get('reason')}")
        if a.get("path"):
            lines.append(f"- Path: `{a.get('path')}`")
        if a.get("evidence"):
            lines.append("- Evidence:")
            for e in a["evidence"][:8]:
                lines.append(f"  - {e}")
        lines.append(f"- Recommendation: {a.get('recommendation')}")
        lines.append("")

    lines += ["## Baseline Diff", ""]
    lines.append(f"- Status: {changes.get('status')}")
    for section in ("added", "removed", "modified"):
        items = changes.get(section) or []
        lines.append(f"### {section.title()} ({len(items)})")
        for it in items[:40]:
            lines.append(f"- `{it}`")
        lines.append("")

    lim = snapshot.get("limitations") or []
    lines += ["## Collection Limitations", ""]
    if not lim:
        lines.append("_None reported._")
    for L in lim:
        lines.append(f"- {L}")
    lines.append("")
    lines.append("---")
    lines.append("Generated by Cora Security Center (Phase 1 READ-ONLY).")
    # Ensure no raw HTML injection if report is later rendered
    return "\n".join(sanitize_for_html(x) if "<" in x and "http" not in x else x for x in lines)
