name: tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  unit:
    name: Unit tests (Linux, Python 3.11)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python -m pytest -q -m unit

  unit-windows:
    name: Unit tests (Windows, Python 3.11)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run unit tests
        shell: pwsh
        run: |
          python -m pytest -q -m unit

